function GenresList() {
     return [
          "action",
          "adventure",
          "cars",
          "comedy",
          "crime",
          "dementia",
          "demons",
          "drama",
          "dub",
          "ecchi",
          "family",
          "fantasy",
          "game",
          "gourmet",
          "harem",
          "historical",
          "horror",
          "josei",
          "kids",
          "magic",
          "martial-arts",
          "mecha",
          "military",
          // "music",
          "mystery",
          "parody",
          "police",
          "psychological",
          "romance",
          "samurai",
          "school",
          "sci-fi",
          "seinen",
          "shoujo",
          "shoujo-ai",
          "shounen",
          "shounen-ai",
          // "slice-of-Life",
          "space",
          "sports",
          "super-power",
          "supernatural",
          "suspense",
          "thriller",
          "vampire",
          "yaoi",
          "yuri",
     ];
}

export default GenresList;